apiVersion: v1
kind: ConfigMap
metadata:
  name: user-workload-monitoring-config
  namespace: openshift-user-workload-monitoring
data:
  config.yaml: |+
    thanosRuler:
      nodeSelector:
        {{ mon_label_key }}: {{ mon_label_value }} 
    prometheusOperator:
      nodeSelector:
        {{ mon_label_key }}: {{ mon_label_value }}
    prometheusK8s:
      retention: {{ retention_period }}
      resources:
        requests:
          cpu: {{ request_cpu }}
          memory: {{ request_mem }}
        limits:
           cpu: {{ limit_cpu }}
           memory: {{ limit_mem }}
