- name: Move csv temmplate to destination
  ansible.builtin.template:
    src: "{{item}}"
    dest: "/var/tmp/{{item | basename | regex_replace('\\.j2$', '') }}"
  with_fileglob:
    - templates/*.j2

- name: apply the created cluster configmap to enable the User defined Pods
  shell: oc apply -f /var/tmp/cluster-monitoring-config.yaml 
  register: config

- name: Check that configmap 
  shell: oc get cm -n openshift-monitoring | grep cluster-monitoring-config
  register: cm_status