- name: Playbook to setuo Mediawiki App
  hosts: [bastionnode]
  gather_facts: yes
  become: true

  tasks:
    - name: Include role for mediawiki DB
      include_role:
        name: DB-Role

    - name: Include role for mediawiki App
      include_role:
        name: App-Role

    - name: Include role for mediawiki Pods Qouta
      include_role:
        name: QoutaLimit
