- name: Move csv & qouta temmplate to destination
  ansible.builtin.template:
    src: "{{item}}"
    dest: "/var/tmp/{{item | basename | regex_replace('\\.j2$', '') }}"
  with_fileglob:
    - templates/*.yaml

- name: apply the qouta limit 
  shell: kubectl apply -f qouta.yaml

- name: apply the created cluster configmap to enable use of csv file for running pods
  shell: kubectl apply -f configmap.yaml
