apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ResourceQuota
  metadata:
    name: podA
  spec:
    hard:
      cpu: "1000"
      memory: 400Gi
      pods: "1"
    scopeSelector:
      matchExpressions:
      - operator : In
        scopeName: PriorityClass
        values: ["A"]
- apiVersion: v1
  kind: ResourceQuota
  metadata:
    name: podB
  spec:
    hard:
      cpu: "10"
      memory: 200Gi
      pods: "1"
    scopeSelector:
      matchExpressions:
      - operator : In
        scopeName: PriorityClass
        values: ["B"]
- apiVersion: v1
  kind: ResourceQuota
  metadata:
    name: podC
  spec:
    hard:
      cpu: "5"
      memory: 400Gi
      pods: "1"
    scopeSelector:
      matchExpressions:
      - operator : In
        scopeName: PriorityClass
        values: ["C"]